baseURL = "/"
languageCode = "id-id"
title = ""
theme = ""

copyright = ""
disqusShortname = ""
enableRobotsTXT = true
enableEmoji = true
googleAnalytics = ""

[Params]
    SiteDescription = ""
    DefaultKeywords = ""

[permalinks]
    post = "/:post/"
    
[taxonomies]
    topic = "topic"

[Author]
    nama = "Saefulloh Maslul"
    web = "https://hobikoding.com"

[outputs]
    home = ["HTML", "JSON", "RSS"]
    article = ["HTML", "JSON", "RSS"]

[menu]

  [[menu.main]]
    identifier = "article"
    name = "This is the blog section"
    title = "blog section"
    url = "/article/"
    weight = 130